// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJBlquMlor1t3udpXSbPTBTn7P_tiu1c',
    appId: '1:730013483269:web:fd6dca1e4025fd4f98f76c',
    messagingSenderId: '730013483269',
    projectId: 'meeras-fest-2027',
    authDomain: 'meeras-fest-2027.firebaseapp.com',
    storageBucket: 'meeras-fest-2027.firebasestorage.app',
    measurementId: 'G-W5TG3V8R15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDW7ceUkBAa3V7d-F4iLcHREQlFUneuA',
    appId: '1:730013483269:android:d6c49e2a68f8e84798f76c',
    messagingSenderId: '730013483269',
    projectId: 'meeras-fest-2027',
    storageBucket: 'meeras-fest-2027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpjf8WfPvlFwcxlUTOcm4LxlEBHLD3XV0',
    appId: '1:730013483269:ios:0569c3cbef018f2c98f76c',
    messagingSenderId: '730013483269',
    projectId: 'meeras-fest-2027',
    storageBucket: 'meeras-fest-2027.firebasestorage.app',
    iosBundleId: 'com.example.meerasFestApp',
  );
}
